### ISSUE TITLE
config.json valitation errors

### ISSUE THREAD

**Issue by riffnshred** [riffnshred/nhl-led-scoreboard#111]
**Describe the bug**
Scoreboard return config.json error in the log and wont work.

**Logs**
: Now validating config.json.....
ERROR (20:48:45): config.json fails validation: error: [data.boards.covid19.country must be array]
ERROR (20:48:45): Rerun the nhl_setup app to create a valid config.json
INFO (20:48:49): NHL-LED-SCOREBOARD - v1.2.1 (64x32)
INFO (20:48:49): Now validating config.json.....
ERROR (20:48:50): config.json fails validation: error: [data.boards.covid19.country must be array]
ERROR (20:48:50): Rerun the nhl_setup app to create a valid config.json
INFO (20:48:54): NHL-LED-SCOREBOARD - v1.2.1 (64x32)
INFO (20:48:54): Now validating config.json.....
ERROR (20:48:54): config.json fails validation: error: [data.boards.covid19.country must be array]
ERROR (20:48:54): Rerun the nhl_setup app to create a valid config.json
INFO (20:48:58): NHL-LED-SCOREBOARD - v1.2.1 (64x32)
INFO (20:48:58): Now validating config.json.....
ERROR (20:48:58): config.json fails validation: error: [data.boards.covid19.country must be array]
ERROR (20:48:58): Rerun the nhl_setup app to create a valid config.json

This is due to nhl_setup putting `null` instead of square bracket `[]` when the user select to not show country stats or canada proving or us states.

**Comment by riffnshred** [comment]
Patial solution is to replace the `null` for `[]` instead. 

Exemple `"country"=null, ` would become `"country=[]"`

**Comment by falkyre** [comment]
For anyone getting these errors and have used the nhl_setup to create your config.json, what are you selecting for the covid boards in the nhl_setup?

**Comment by falkyre** [comment]
Also for anyone getting this, do you already have an existing config.json when you run the nhl_setup?

**Comment by riffnshred** [comment]
I believe this was fixed or just a compatibility problem between config files of different versions.
