### ISSUE TITLE
After seeing a NWS alert for air quality, the 4th weather page only displays black

### ISSUE THREAD

**Issue by vorin615** [riffnshred/nhl-led-scoreboard#115]
I received an Air Quality Alert from the NWS today, which displayed large text scrolling across the screen.
Before then, I had never seen a 4th weather page, it always continued onto the div standings.
Now, I no longer see the scrolling text but the screen is completely black before continuing on.
I never noticed any square indicator on the clock page, but I also do not have weather info below the time (in case that matters.)

```

INFO (16:39:34): Checking for new day
INFO (16:39:34): It is not a new day
INFO (16:39:46): Checking NWS weather alerts
INFO (16:39:52): Number of alerts is 1
INFO (16:39:52): ['Air Quality Alert', 'statement', '07/14 01:58 PM', 'Unknown', 'Unknown']
INFO (16:40:06): Refreshing OWM current observations weather
INFO (16:40:08): ['07/14 04:40 PM', '\uf002', 'scattered clouds', '90.8F', '91.4F', '38%', '67.1F']
INFO (16:40:08): ['5.8mph', 'S', '\uf05c', '0mph', '1016 MB', '\uf07b', '10.0 mi']
INFO (16:43:39): Checking for new day
```

**Your config file**
https://pastebin.com/nTKykiFi

**Hardware you are using**
- Raspberry Pi Zero W
- Adafruit Bonnet
- Yes pwm fix(pin 4/18)

**Software**
V1.2.1 Beta
Commit 12f182e

**Comment by falkyre** [comment]
As mentioned in discord, statements aren't supposed to be handled.  I will fix it once I'm back from vacation
