### ISSUE TITLE
Pressure Indicator Not Displaying

### ISSUE THREAD

**Issue by jeepdrvr71** [riffnshred/nhl-led-scoreboard#119]
On the pressure screen(US weather) everything displays correctly except for the indicator if the pressure is rising or falling. Not sure if it's because they don't pass that data along. On my display it say "N/A." I there a way to remove the "N/A"  if there isn't a fix available?

**Comment by falkyre** [comment]
I'll remove it on next patch.  Open weather map does not supply the pressure tendency so I'll remove it.
