### ISSUE TITLE
V1.3 Install issue

### ISSUE THREAD

**Issue by notthatpaulyd** [riffnshred/nhl-led-scoreboard#128]
**Describe the bug**
Might be more of a user error than a bug. After running git reset —hard and then git fetch origin —prune I get error:
 error: cannot open .git/FETCH_HEAD: Permission denied

**Software**
- Which version of the software are you on?
V1.2.1

**Comment by riffnshred** [comment]
as discussed in the help chat on discord, you have to run the following command from the root of the nhl-led-scoreboard folder

`sudo chown -R pi:pi .git`
