### ISSUE TITLE
did the update to 1.3.2, but scoreboard is still giving green bar at top. 

### ISSUE THREAD

**Issue by cmcurtis33** [riffnshred/nhl-led-scoreboard#135]
Did the update to 1.3.2, but scoreboard is still giving green bar at top. 

Seems the issue could be that VERSION file is still having 1.3.1. Not a big deal but reporting in case others are also seeing.

**Comment by riffnshred** [comment]
sorry about that mate, I just bumped the version in VERSION file. let me know if that didn fix it

**Comment by cmcurtis33** [comment]
Yes that worked.. glad it was an easy fix. Thanks again for all that you are doing to make the hockey season more enjoyable -- and have a cool toy to keep track of scores while I'm working!

**Comment by riffnshred** [comment]
Thanks man , glad you enjoy !!! Fun fact I made this thing to also keep track of scores while I'm working !!!

Cheers !!!
