### ISSUE TITLE
Black box for scoreboard (Case)

### ISSUE THREAD

**Issue by msroth** [riffnshred/nhl-led-scoreboard#14]
I like be black box the scoreboard in the photo is in.  Did you make it or buy it?  Care to share the details?

**Comment by riffnshred** [comment]
It`s a 3D printed case I found on another project. the issue with it is that it`s not made to have a Raspberry pi in it. Some are working on making a proper one

**Comment by mrdink** [comment]
A great tutorial on how to make one is located here https://howchoo.com/g/otvjnwy4mji/diy-raspberry-pi-nhl-scoreboard-led-panel

I had to modify the model to fit my screen but it worked out great.

![IMG_0172](https://user-images.githubusercontent.com/514751/71935440-c6d47080-3174-11ea-9573-af6b0c506c3a.jpeg)

**Comment by joshkay** [comment]
What size screen do you have?

**Comment by mrdink** [comment]
> What size screen do you have?

It’s the same size but it doesn’t have the frame on the back of it.

https://www.amazon.com/dp/B07S2VZ13G?ref=ppx_pop_mob_ap_share

**Comment by riffnshred** [comment]
Oooh kk you got the flexible version. Glad it fit in the case after all
