### ISSUE TITLE
Add weather conditions to clock board instead of humidity

### ISSUE THREAD

**Issue by twfarley** [riffnshred/nhl-led-scoreboard#146]
Humidity isn't that important where I'm at. It would be nice to see "Cloudy", "Clear", Rain, etc.

Loving this so far, though!

**Comment by falkyre** [comment]
The current conditions are already on the first page of the weather.  You can select a summary view in the config and you'll only get the first page.

**Comment by twfarley** [comment]
Changing to self.data.wx_current[2] gets the data I like. Thanks.
