### ISSUE TITLE
change font?

### ISSUE THREAD

**Issue by machinasdei** [riffnshred/nhl-led-scoreboard#148]
whats the easiest way to change the font on the scoreboard and the covid19 display?  sorry i suck at scripting and dont understand how to make the change.  (been trying to figure it out)  the 6's and 9's p's q's other letters are difficult for me to read on the display.  (using the standard 32x16)

**Comment by riffnshred** [comment]
Add the font file in asset/font then open config/font/font.json. I recommend duplicating the medium_2 and change its name (ex:medium_3) and change the file name too the one you added in the asset. 

Finally, go under config/layout/layout.json and in the covid_19 section, change the font of Count from medium_2 to what ever you named your new font.

That should do the trick. 
Cheers
