### ISSUE TITLE
Won’t boot directly into scoreboard

### ISSUE THREAD

**Issue by drodgers24** [riffnshred/nhl-led-scoreboard#158]
Building out a scoreboard and needing to get it to run stand alone and boot directly into the scoreboard program. I have the power button added and it works. I followed the instruction to use supervisor but when I reboot it will boot like normal and ask for username and password and won’t boot up scoreboard program. 

Am I missing a step?

Thanks!

**Comment by jlm4487** [comment]
It will always boot to the username and password when it reboots but supervisor should start up the app in the background. Can you access supervisor via the web browser? If so, what does it show?

**Comment by drodgers24** [comment]
It does pull up and show running when I pull up supervisor on the web. The issue is that this is going to be a gift for someone else and was hoping they would be able to just turn it on and have it run without having to login. Is there a way around the login or another option to be able to have them just start it?

**Comment by riffnshred** [comment]
Just found out some issues with the last update. I'll work on that tonight and try to push a fix. Sorry about that

**Comment by riffnshred** [comment]
can you confirm your issue is resolved? I believe the issue was with bad config in Supervisor right?

**Comment by riffnshred** [comment]
closing do to no update from OP
