### ISSUE TITLE
Missing json file

### ISSUE THREAD

**Issue by jeepdrvr71** [riffnshred/nhl-led-scoreboard#160]
Just updated the scoreboard and got it all working yesterday This morning it stopped working and got the following error in Supervisor. I'm running the latest version.

fig file config/layout/layout_64x32.json not found!
Config file config/fonts/fonts_64x32.json not found!
Config file config/layout/layout_64x32.json not found!
Config file config/fonts/fonts_64x32.json not found!
Config file config/layout/layout_64x32.json not found!
Config file config/fonts/fonts_64x32.json not found!
Config file config/layout/layout_64x32.json not found!
Config file config/fonts/fonts_64x32.json not found!
Config file config/layout/layout_64x32.json not found!
Config file config/fonts/fonts_64x32.json not found!
Config file config/layout/layout_64x32.json not found!
Config file config/fonts/fonts_64x32.json not found!
Config file config/layout/layout_64x32.json not found!
Config file config/fonts/fonts_64x32.json not found!
Config file config/layout/layout_64x32.json not found!
Config file config/fonts/fonts_64x32.json not found!
Config file config/layout/layout_64x32.json not found!
Config file config/fonts/fonts_64x32.json not found!
Config file config/layout/layout_64x32.json not found!

**Comment by falkyre** [comment]
That's a normal "error".  The board is not running because there's been a change in the NHL data feed that breaks the code.

**Comment by jeepdrvr71** [comment]
Did this just happen in the last 24 hours?

**Comment by falkyre** [comment]
Yup

**Comment by riffnshred** [comment]
Fix with version 1.5.4
