### ISSUE TITLE
"no game today"

### ISSUE THREAD

**Issue by PHI34Halladay** [riffnshred/nhl-led-scoreboard#17]
Hey guys,
I just installed the NHL Scoreboard. I'm using the MLB Scoreboard since early April 2019 and just found out that there is a NHL version :)

My problem now is that whatever I do, I only get the "no game today" info. I tried changing the favorite team id to a team playing today in the config.json and by using the --fav-team flag without any results.
It's January 20th today and Detroit is playing but using the ID "17" still gives me the same info:

INFO (11:04:28): NHL Scoreboard - v0.1.0 (64x32)
INFO (11:04:29): Off day State
INFO (11:04:29): ping_day_off

Is there an option somewhere to check the correct date?

Please help me out here.

Regards,
Patrick

**Comment by riffnshred** [comment]
How is it now?

**Comment by PHI34Halladay** [comment]
Works like a Charme :)

**Comment by riffnshred** [comment]
It's because the API update to that new day at Noon everyday ;). On the new version that's coming out, you can set at what time you want the board to update to the new day. 

Cheers
