### ISSUE TITLE
not loading setup

### ISSUE THREAD

**Issue by ceegmac** [riffnshred/nhl-led-scoreboard#173]
Hi, just trying to get scoreboard to load after install however i keep getting setup error
 ________________  _____
  / __/ __/_  __/ / / / _ \
 _\ \/ _/  / / / /_/ / ___/
/___/___/ /_/  \____/_/

1.5.0
Traceback (most recent call last):
  File "nhl_setup.py", line 1605, in <module>
  File "nhl_setup.py", line 1518, in main
PermissionError: [Errno 13] Permission denied: 'config/.default/firstrun'
[1130] Failed to execute script nhl_setup
pi@raspberrypi:~/nhl-led-scoreboard $

not sure what i am doing wrong. worked before update but not after. i can get the test screen to work however

**Comment by riffnshred** [comment]
that is because the firstrun file is missing.

you can create one by running this from the nhl-led-scoreboard directory

`touch config/.default/firstrun`

**Comment by ceegmac** [comment]
it says permission denied

**Comment by riffnshred** [comment]
Also heads up. an update is pending for tomorrow morning after testing with the first live game tonight. Standings, seriesticker and stanley_cup_champions boards are not working at the moment.

**Comment by riffnshred** [comment]
what is you do `sudo touch config/.default/firstrun`

**Comment by ceegmac** [comment]
got this now

Traceback (most recent call last):
  File "nhl_setup.py", line 1605, in <module>
  File "nhl_setup.py", line 1518, in main
PermissionError: [Errno 13] Permission denied: 'config/.default/firstrun'
[1602] Failed to execute script nhl_setup

**Comment by riffnshred** [comment]
you'll have to run the nhl_setup with sudo (which is not ideal, we are figuring those issues out on our end)

so run `sudo ./nhl_setup`

That should work

**Comment by ceegmac** [comment]
yes worked thnx
