### ISSUE TITLE
Read me addition

### ISSUE THREAD

**Issue by SL-8596** [riffnshred/nhl-led-scoreboard#179]
Suggested addition to the Read Me:

list of the most commonly used commands for the scoreboard.

**Comment by riffnshred** [comment]
After thinking about it, this is not a good idea. There is not such thing as commonly used commands other then the ones that are needed to install and run. Everything else depends on what you want to do. 

I strongly recommend learning to navigate the repository and do different things in a terminal. Any time I try to do something and I'm not sure how, I check google and I usually find what I need quickly. 

Here's a great place to start. https://www.raspberrypi.org/documentation/linux/usage/commands.md
