### ISSUE TITLE
LED Refresh Rate Limiter broke

### ISSUE THREAD

**Issue by twfarley** [riffnshred/nhl-led-scoreboard#182]
Traceback (most recent call last):
  File "src/main.py", line 139, in <module>
    run()
  File "src/main.py", line 43, in run
    matrixOptions = led_matrix_options(commandArgs)
  File "/home/pi/nhl-led-scoreboard/src/utils.py", line 128, in led_matrix_options
    options.limit_refresh_rate_hz = args.led_limit_refresh
AttributeError: 'rgbmatrix.core.RGBMatrixOptions' object has no attribute 'limit_refresh_rate_hz'

**Comment by riffnshred** [comment]
Are you on v1.5.5?

**Comment by twfarley** [comment]
Yep.

**Comment by riffnshred** [comment]
it does work on my end. can you show me the command you use to run your board ?

**Comment by twfarley** [comment]
`sudo python3 src/main.py --led-gpio-mapping=adafruit-hat-pwm`

**Comment by riffnshred** [comment]
check the status of the submodule
`git submodule status`. copy what it gives you here

**Comment by twfarley** [comment]
```
$ git submodule status
 84e1465e9ea5ed000011d05369c5287eaa361ad7 submodules/matrix (remotes/origin/pixel-mapper-206-g84e1465)
```

**Comment by riffnshred** [comment]
thats a weird one. you are on the right version of the submodule. You updated from which version do you know ?

**Comment by riffnshred** [comment]
If shows you that error on startup no matter what? If so I would delete the repo and reclone and reconfig.

**Comment by falkyre** [comment]
You have to reinstall the rgb matrix library.  Run through the whole make and compile and o
Pip install. I've done it for two if my boards that had same issue and the rgb matrix install steps fixed it

**Comment by twfarley** [comment]
Sure. You should probably make a note of that in the commit.
