### ISSUE TITLE
Update readme.md to Reflect Change in --Updatecheck

### ISSUE THREAD

**Issue by kattivo1** [riffnshred/nhl-led-scoreboard#183]
Incorrect language:

Update checker
Now the scoreboard has an Update checker option where it will show a green line on top of the screen if there is a new Major or minor update. To use it simply add the --updatecheck flag to the command line you use to run the board and set it to true of false like so --updatecheck=True.

Per @falkyre, this feature no longer requires a flag. Since I had a remnant flag in my Supervisor configuration file, it was causing the program to crash. Once I removed it, I was good again.

**Comment by falkyre** [comment]
See https://github.com/riffnshred/nhl-led-scoreboard/pull/144
