### ISSUE TITLE
Fission Reactor Help

### ISSUE THREAD

**Issue by rhazzed** [riffnshred/nhl-led-scoreboard#195]
I am trying to connect my reactor to my scoreboard, to activate when an opposing team scores a goal.

**Comment by riffnshred** [comment]
![tenor 1](https://user-images.githubusercontent.com/16941896/106029003-a2f30e00-609a-11eb-85e7-825f7fc317c3.png)

**Comment by rhazzed** [comment]
~ Eric/n9rzr
