### ISSUE TITLE
Addition for installation process

### ISSUE THREAD

**Issue by desigi** [riffnshred/nhl-led-scoreboard#2]
Great project! Thanks for doing this. I have everything setup and I'm really liking it.

One thing I noticed when initially wanting to run the main.py file, I would initially get an error
`ImportError: No module named requests`

I had to run `pip install requests` to get rid of that error. Now everything runs smoothly.

**Comment by riffnshred** [comment]
I added it to the install.sh and the README. Not going to be able to test it tonight but it should install automatically now.

I'll close the issue once I test it
