### ISSUE TITLE
Scores not updating when favorite team is not playing that day

### ISSUE THREAD

**Issue by Coop21** [riffnshred/nhl-led-scoreboard#229]
**Describe the bug**
My favorite is set as Kings.  All scores updated without issue last night, as the Kings had a game.  The Kings are not playing today and the only time scores are updating is when the program first starts.  I changed my favorite to Flames, who are playing tonight, and restarted the program.  All scores updated without issue.  

**Logs**
Copy and past any error or messages that you can get. 

**Your config file**
A screen shot of your config.json file can be really useful to help you. 

{
    "debug": false,
    "loglevel": "INFO",
    "live_mode": true,
    "preferences": {
        "time_format": "12h",
        "end_of_day": "8:00",
        "location": "",
        "live_game_refresh_rate": 10,
        "teams": [
            "Kings"
        ],
        "sog_display_frequency": 4,
        "goal_animations": {
            "pref_team_only": true
        }
    },
    "states": {
        "off_day": [
            "scoreticker",
            "seriesticker",
            "team_summary",
            "clock"
        ],
        "scheduled": [
            "scoreticker"

        ],
        "intermission": [
            "scoreticker",
            "clock"
        ],
        "post_game": [
            "scoreticker",
            "seriesticker",
            "team_summary",
            "clock"
        ]
    },
    "boards": {
        "scoreticker": {
            "preferred_teams_only": false,
            "rotation_rate": 5
        },
        "seriesticker": {
            "preferred_teams_only": false,
            "rotation_rate": 5
        },
        "standings": {
            "preferred_standings_only": false,
            "standing_type": "division",
            "divisions": "west",
            "conference": "western"
        },
        "clock": {
            "duration": 5,
            "hide_indicator": false,
            "preferred_team_colors": true,
            "clock_rgb": "",
            "date_rgb": "",
            "flash_seconds": true
        },
        "covid19": {
            "worldwide_enabled": false,
            "country_enabled": false,
            "country": [
                "USA"
            ],
            "us_state_enabled": false,
            "us_state": [
                "New York"
            ],
            "canada_enabled": false,
            "canada_prov": [
                "Quebec"
            ]
        },
        "weather": {
            "enabled": false,
            "view": "full",
            "units": "metric",
            "duration": 60,
            "data_feed": "EC",
            "owm_apikey": "",
            "update_freq": 5,
            "show_on_clock": true,
            "forecast_enabled": false,
            "forecast_days": 3,
            "forecast_update": 1
        },
        "wxalert": {
            "alert_feed": "EC",
            "update_freq": 5,
            "show_alerts": false,
            "nws_show_expire": false,
            "alert_title": true,
            "scroll_alert": true,
            "alert_duration": 5,
            "show_on_clock": true
        }
    },
    "sbio": {
        "screensaver": {
            "enabled": false,
            "animations": true,
            "start": "22:00",
            "stop": "08:00",
            "data_updates": false,
            "motionsensor": false,
            "pin": 7,
            "delay": 30
        },
        "dimmer": {
            "enabled": false,
            "source": "software",
            "daytime": "",
            "nighttime": "",
            "offset": 0,
            "frequency": 5,
            "light_level_lux": 400,
            "mode": "always",
            "sunset_brightness": 5,
            "sunrise_brightness": 40
        },
        "pushbutton": {
            "enabled": false,
            "bonnet": false,
            "pin": 25,
            "reboot_duration": 2,
            "reboot_override_process": "",
            "display_reboot": true,
            "poweroff_duration": 10,
            "poweroff_override_process": "",
            "display_halt": true,
            "state_triggered1": "weather",
            "state_triggered1_process": ""
        }
    }
}

**Hardware you are using**
- Raspberry pi 4b
- Adafruit - Anti-flicker mod o not? 

**Software**
- Which version of the software are you on? 1.6

**Comment by riffnshred** [comment]
found why. On the last update I removed and modified a bunch of stuff to reduce the number of call to the API when there is no game. There are some people with limited data that uses this project and they got some surprised in their internet bill over the playoff last summer. 

because of that, I removed the `refresh_data()` from the off_day state thinking no one is staring at this thing when there fav team is not playing. Doh !!!!! 

I will put it back in on the upcoming fix Im working on and I will change how the live_mode works with a couple of options to refresh the data in different ways.

thanks for reporting !!!
