### ISSUE TITLE
Solid green bar across the top row

### ISSUE THREAD

**Issue by JoeFromDenver** [riffnshred/nhl-led-scoreboard#247]
I started from scratch using the pre-built .img file on both a Pi Zero WH and 3B+ with the no flicker mod. 

I don't see any errors in the logs. Any idea what might cause this? The green bar doesn't show up when loading, or on other screens, but it's there 75% of the time when the scoreboard is in use.

![PXL_20210313_194028561](https://user-images.githubusercontent.com/45112027/111043773-984dc780-8401-11eb-86b2-d24338abad4a.jpg)
![PXL_20210313_194612925](https://user-images.githubusercontent.com/45112027/111043774-9ab02180-8401-11eb-9373-a34928e26c56.jpg)

**Comment by JoeFromDenver** [comment]
Updated to the newest version and it's working as expected. Not sure what was going on there, but it looks great now!

**Comment by riffnshred** [comment]
Thats the update notification indicator. You can set it to false in the config.

**Comment by JoeFromDenver** [comment]
Fantastic, thanks! That makes a lot of sense in hindsight.

Follow-up simple question. I can't find that option in config.json (or the sample) and when I searched for "update notification" in the documentation I don't see it mentioned. I'd love to set that option to false, can you point me in the right direction?

**Comment by riffnshred** [comment]
Actually, Im wrong, do you have `--updatecheck` in the command you use to run the scoreboard ?

**Comment by falkyre** [comment]
The image puts the update checker in automatically for your supervisor config. It's a command line option.

**Comment by riffnshred** [comment]
One way to remove it then is to open the supervisor conf file

`sudo nano /etc/supervisor/conf.d/scoreboard.conf`

and you will see the command that supervisor use to run the scoreboard, find `--updatecheck` and remove it.

**Comment by riffnshred** [comment]
I will add it as an option in the config on the next update so you can have it on or off, however you want it

**Comment by JoeFromDenver** [comment]
Very cool, thank you!
