### ISSUE TITLE
**Integrate a new Matrix class***

### ISSUE THREAD

**Issue by riffnshred** [riffnshred/nhl-led-scoreboard#25]
To make rendering an easier task, Duetoxplode proposed a new Matrix class that is a wrapper for both PIL and the rgbmatrix rendering functions.

**Comment by joshkay** [comment]
Excited to get going. Will get a pr done tomorrow. Feel free to assign me here :+1:

**Comment by riffnshred** [comment]
Tested and works as intended. I added the Network Indicator function on there too. Great work
