### ISSUE TITLE
NFL scoreboard

### ISSUE THREAD

**Issue by WashCaps33** [riffnshred/nhl-led-scoreboard#251]
Any intent on developing an NFL scoreboard much like the NHL and MLB ones?

**Comment by falkyre** [comment]
Not by us but there are others who have develop an NFL one:  https://github.com/mikemountain/nfl-led-scoreboard

**Comment by riffnshred** [comment]
That one was based off a previous version or mine. Its still a work in progress I think. I don't intend to make one my self.
