### ISSUE TITLE
Board Keeps Resetting and Going to Loading Screen

### ISSUE THREAD

**Issue by JackLSamuelson** [riffnshred/nhl-led-scoreboard#260]
Every time I start the board, it runs for maybe 2-3 minutes and then shutdown and restarts.

**Comment by riffnshred** [comment]
run it in a terminal directly, see what error pops up

**Comment by JackLSamuelson** [comment]
![Capture03272021](https://user-images.githubusercontent.com/79265385/112732228-21d7bc00-8f0f-11eb-8c33-491654fb3af1.PNG)
This is the error i get before it shuts down and restarts

**Comment by riffnshred** [comment]
You need to change the division in your config to either, 

"east", "west", "north", "central"

**Comment by JackLSamuelson** [comment]
that fixed it thank you!
