### ISSUE TITLE
Power Supply Question

### ISSUE THREAD

**Issue by jwallner0710** [riffnshred/nhl-led-scoreboard#281]
I upgraded to a 3A with a rgb matrix bonnet. 

Do you guys plug your power supply into the rgb matrix bonnet or the raspberry pi?

**Comment by riffnshred** [comment]
you need to Power the Matrix Bonnet. checkout the hardware section for all the details.

https://github.com/riffnshred/nhl-led-scoreboard/wiki/Hardware
