### ISSUE TITLE
1.6.4. update breaks board rendering

### ISSUE THREAD

**Issue by rentiak** [riffnshred/nhl-led-scoreboard#284]
**Describe the bug**
The latest playoff 1.6.4 release breaks rendering of certain text fields.

![image](https://user-images.githubusercontent.com/3512400/118414923-62cd9080-b675-11eb-8da4-9a1b2c5ee04b.png)

![image](https://user-images.githubusercontent.com/3512400/118414927-66f9ae00-b675-11eb-9863-31c8454b287c.png)

**Comment by riffnshred** [comment]
This is caused by the latest update to Pillow , which is what we use to generate the image that the screen render.

try uninstalling it 

sudo pip3 uninstall pillow

and then rerun the update procedure.

```
git reset --hard
git checkout master
git pull
chmod +x scripts/install.sh
./scripts/install.sh
```

**Comment by rentiak** [comment]
That worked for me. Series ticket and weather board (pictures above) both render correctly now.

**Comment by riffnshred** [comment]
Perfect. Thanks bud !
