### ISSUE TITLE
Sudo ./install.sh

### ISSUE THREAD

**Issue by riffnshred** [riffnshred/nhl-led-scoreboard#3]
If it does not work, do `sudo bash ./install.sh`. 

Ill fix it in the readme file when I get back from trip.

**Comment by ajbowler** [comment]
@riffnshred the issue is a permissions issue, when cloning it the file doesn't have executable permissions.

**Comment by ajbowler** [comment]
chmod'ing it with 777 is a quick fix

**Comment by ZLevine** [comment]
I came across this issue too—I just submitted [a PR](https://github.com/riffnshred/nhl-led-scoreboard/pull/10) that addresses this in the documentation.

tl;dr; You need to [make the shell script executable using this approach](https://howchoo.com/g/yzfhzjhjogm/how-to-make-a-shell-script-executable-on-the-raspberry-pi).
