### ISSUE TITLE
Delay in iterating past the last team on score ticker board

### ISSUE THREAD

**Issue by ntjoumas** [riffnshred/nhl-led-scoreboard#30]
When displaying the score ticker board, all teams iterate through respective to the delay set in rotation_rate within config.json except for the last team, which seems to have a delay of around 20 seconds.

**Comment by joshkay** [comment]
No longer seeing this happen on the dev branch.

**Comment by riffnshred** [comment]
Will leave open til release, but I also no longer see it.
