### ISSUE TITLE
Keep Getting Stuck on Loading Screen

### ISSUE THREAD

**Issue by Bradw-17** [riffnshred/nhl-led-scoreboard#331]
After flashing and configuring the latest version (1.6.8) I reboot the Pi to ensure everything works, and it gets hung up on the loading screen. 

The only thing I change after basic setup is the led-slowdown-gpio from 0 to 2 (maybe this should be the default for when a user chooses the 64x32 with antiflicker option). 

It does stop the flickering, but doesn't help if it gets stuck on the loading screen forever lol

**Comment by Bradw-17** [comment]
Here's the log:

2021-10-28 22:46:27 INFO NHL-LED-SCOREBOARD - v1.6.8 (64x32)
2021-10-28 22:46:27 INFO location loaded from cache (saved -1 days ago): XXXXXX, CA [XX.XXXX, -XX.XXX]
2021-10-28 22:47:16 INFO NHL-LED-SCOREBOARD - v1.6.8 (64x32)
2021-10-28 22:47:17 INFO location loaded from cache (saved -1 days ago): XXXXXX, CA [XX.XXXX, -XX.XXX]
2021-10-28 22:48:07 INFO NHL-LED-SCOREBOARD - v1.6.8 (64x32)
2021-10-28 22:48:07 INFO location loaded from cache (saved -1 days ago): XXXXXX, CA [XX.XXXX, -XX.XXX]
2021-10-28 22:48:56 INFO NHL-LED-SCOREBOARD - v1.6.8 (64x32)
2021-10-28 22:48:56 INFO location loaded from cache (saved -1 days ago): XXXXXX, CA [XX.XXXX, -XX.XXX]
2021-10-28 22:49:45 INFO NHL-LED-SCOREBOARD - v1.6.8 (64x32)
2021-10-28 22:49:45 INFO location loaded from cache (saved -1 days ago): XXXXXX, CA [XX.XXXX, -XX.XXX]

(Location info is accurate, X'd out for privacy)

**Comment by riffnshred** [comment]
did you use the nhl-led-scoreboard-img to install it or did you install the standard raspberry pi OS Lite and installed the nhl-led-scoreboard manually.

If you try running from a terminal, does it crash or it does the same thing (show the loading screen on loop), if so, what are the errors that comes up?

**Comment by ricky-hammers** [comment]
I am having the exact same issue on a fresh install as well

**Comment by riffnshred** [comment]
Can you copy and paste your config (X out your location)?

**Comment by ricky-hammers** [comment]
I flashed it twice and got to the same flashing loading screen each time.

pi@scoreboard-c02e: ~/nhl-led-scoreboard (master)$ view config
        }
glevel": "INFO",
    "live_mode": true,
    "preferences": {
        "time_format": "12h",
        "end_of_day": "8:00",
        "location": "",
        "live_game_refresh_rate": 10,
        "teams": [
            "Rangers"
        ],
        "sog_display_frequency": 4,
        "goal_animations": {
            "pref_team_only": true
        }
    },
    "states": {
        "off_day": [
            "team_summary",
            "clock"
        ],

~/nhl-led-scoreboard/config/config.json [+]                   37,1           12%
-- INSERT --

**Comment by Bradw-17** [comment]
I used the nhl-led_scoreboard-img.

error: <class 'xml.parsers.expat.ExpatError'>, not well-formed (invalid token): line 17, column 0: file: /usr/lib/python3.7/xmlrpc/client.py line: 439

**Comment by Bradw-17** [comment]
{
    "debug": false,
    "loglevel": "INFO",
    "live_mode": true,
    "preferences": {
        "time_format": "12h",
        "end_of_day": "8:00",
        "location": "",
        "live_game_refresh_rate": 10,
        "teams": [
            "Maple Leafs"
        ],
        "sog_display_frequency": 4,
        "goal_animations": {
            "pref_team_only": true
        }
    },
    "states": {
        "off_day": [
            "team_summary",
            "clock"
        ],
        "scheduled": [
            "team_summary",
            "scoreticker",
            "clock"
        ],
        "intermission": [
            "scoreticker",
            "team_summary"
        ],
        "post_game": [

**Comment by Bradw-17** [comment]
@txrangersxx seems to be correct in that the location is blank.

**Comment by riffnshred** [comment]
Those are only part of the whole config. 

@Bradw-17 since you are using the nhl-led-scoreboard-img, you have a few tools available. [checkout that repository](https://github.com/falkyre/nhl-led-scoreboard-img#NHL-Led-Scoreboard-command-line-utilities) for my detail. try running `sb-issue`. This should render a link you can paste here

**Comment by ricky-hammers** [comment]
https://pastebin.ubuntu.com/p/Fts4TZNx86/

**Comment by Bradw-17** [comment]
http://paste.ubuntu.com/p/HrHnPfXmjK/

**Comment by riffnshred** [comment]
@Bradw-17 I deleted yours because it contained sensitive info. 

Im not the one who worked on the part of the code that need this but, it seems like its an issue related to Multiple timezone comflict. 

Try changing your timezone in the raspi-config. to open it run `sudo raspi-config` the timezone is in the Localisation menu. try changing it to a location that is the closest to you. for exemple if you are in Montreal and its set to Toronto, change it to Montreal

**Comment by ricky-hammers** [comment]
didn't work but thanks for the advice, I guess I should try a manual build?

**Comment by riffnshred** [comment]
Im not sure its related to the nhl-led-scoreboard image. you can try , but if I was you I'd try it on an other SC card if you have an other one so you dont have to redo the whole process with the image

**Comment by riffnshred** [comment]
I'll try to replicate this using you config

**Comment by falkyre** [comment]
> didn't work but thanks for the advice, I guess I should try a manual build?

Are you familiar with linux command line tools and editing files?

Can you do the following: 
```
sudo su -
cat /etc/timezone 
```
What's it show?

**Comment by Bradw-17** [comment]
Shows "America/Toronto" which is accurate

**Comment by Bradw-17** [comment]
I'm not super familiar but I manage my way through lol

**Comment by ricky-hammers** [comment]
America/New york which is accurate enough

**Comment by riffnshred** [comment]
Is it possible you guys use a VPN?

**Comment by falkyre** [comment]
Run this and let me know what get's returned back:

```zone=$(/usr/bin/wget -O - -q http://geoip.ubuntu.com/lookup | sed -n -e 's/.*<TimeZone>\(.*\)<\/TimeZone>.*/\1/ p')
echo $zone
```

**Comment by Bradw-17** [comment]
Nope

**Comment by Bradw-17** [comment]
America/Toronto

**Comment by ricky-hammers** [comment]
it returns america/new york which is accurate for me

**Comment by falkyre** [comment]
OK,

what does this show 
```
 pip3 show tzlocal
```

**Comment by Bradw-17** [comment]
Name: tzlocal
Version: 4.0.2
Summary: tzinfo object for the local timezone
Home-page: UNKNOWN
Author: Lennart Regebro
Author-email: regebro@gmail.com
License: MIT
Location: /usr/local/lib/python3.7/dist-packages
Requires: backports.zoneinfo, pytz-deprecation-shim
Required-by: APScheduler

**Comment by falkyre** [comment]
> Name: tzlocal Version: 4.0.2 Summary: tzinfo object for the local timezone Home-page: UNKNOWN Author: Lennart Regebro Author-email: [regebro@gmail.com](mailto:regebro@gmail.com) License: MIT Location: /usr/local/lib/python3.7/dist-packages Requires: backports.zoneinfo, pytz-deprecation-shim Required-by: APScheduler

Now what about 

``` 
ls -la /etc/localtime
```

**Comment by Bradw-17** [comment]
lrwxrwxrwx 1 root root 35 Oct 29 18:45 /etc/localtime -> /usr/share/zoneinfo/America/Toronto

The time is wrong, it should be about 19:22

**Comment by falkyre** [comment]
> lrwxrwxrwx 1 root root 35 Oct 29 18:45 /etc/localtime -> /usr/share/zoneinfo/America/Toronto
> 
> The time is wrong, it should be about 19:22

That time is when the file was created but it matches what's in your /etc/timezone which it should.

So, I guess the only other question is, did you modify the config.json to add any of the weather stuff, or screensaver?  That's where the error is coming from.

Does your ``` pip3 show APScheduler | grep Version ``` show Version: 3.8.1?

**Comment by Bradw-17** [comment]
No, literally the only thing I changed was from `led-slowdown-gpio=0` to `led-slowdown-gpio=2`

**Comment by Bradw-17** [comment]
The method I used to change it was by running this command:

`sudo nano /etc/supervisor/conf.d/scoreboard.conf`

And then editing the 0 to 2. Then I exited and saved changes.

Other than that everything is stock after initial setup, and although it flickers, it does work until this change is made. Then the flickering stops, but it hangs up on the flashing loading screen.

**Comment by falkyre** [comment]
> No, literally the only thing I changed was from `led-slowdown-gpio=0` to `led-slowdown-gpio=2`
> 
> And it does show 3.8.1

OK,

The scheduler still gets launched even if you don't use it.  Have you run the raspi-config to force a set of your timezone?  As my image is working fine and @riffnshred  just tested one as well and it worked fine, I'm not able to really troubleshoot without making some guesses 

if you run ``` sudo /home/pi/sbtools/autoset_tz.sh ```

what's it return?

**Comment by Bradw-17** [comment]
`Timezone America/Toronto already set correctly for your location found(America/Toronto)`

**Comment by riffnshred** [comment]
At this point, I think the issue might be really specifique for some reason. 

Try doing a manual install using a standard raspberry pi image and see if that works.

https://github.com/riffnshred/nhl-led-scoreboard/wiki/Step-by-step-guide.

**Comment by Bradw-17** [comment]
Alrighty, I'll give it a shot. Really appreciate you both @riffnshred and @falkyre for taking the time to look at this! I'll run the manual install and let you know what happens!

Just curious, if in the optimal performance section you've got the led-slowdown-gpio=2, should that maybe be a default for that particular screen option or would that cause conflicts elsewhere?

**Comment by riffnshred** [comment]
no problem !!

Yes, that is specifically for the Pi 3 and 4. Also, have you done the antiflicker Mod? If so, make sure you disabled the audio (details in that section) and use the right --led-gpio-mapping option in your command.

Without the antiflicker mod you need to use `--led-gpio-mapping=adafruit-hat`
with the antiflicker mod `--led-gpio-mapping=adafruit-hat-pwm`

**Comment by Bradw-17** [comment]
Yeah, I've done the hardware mod and selected the "64x32 with flicker mod" option on setup.
dtparam=audio=off is already set in config.txt
And my led-gpio-mapping=adafruit-hat-pwm

**Comment by falkyre** [comment]
> Alrighty, I'll give it a shot. Really appreciate you both @riffnshred and @falkyre for taking the time to look at this! I'll run the manual install and let you know what happens!
> 
> Just curious, if in the optimal performance section you've got the led-slowdown-gpio=2, should that maybe be a default for that particular screen option or would that cause conflicts elsewhere?

The image was created to get you up and running with the widest range possible for available raspberry pis that were out there.  With the new raspberry pi zero 2 w coming out, I'll look at making the configuration based on the raspberry pi type that the image is being installed on.  I have a couple on order so once I get them, I'll make some changes to the image to do this.

**Comment by falkyre** [comment]
@Bradw-17 Do you still have the image that's not working available?  The guys that wrote the tzlocal librarys **_JUST_**  released a new version and I'd like to see if it fixes your issue.  If so can you do this:

```
sudo pip3 uninstall tzlocal
sudo pip3 install tzlocal

```

Let me know if it helps

**Comment by Bradw-17** [comment]
Bingo! Working now!! Thanks @falkyre !!!

**Comment by riffnshred** [comment]
![dwight-the-office](https://user-images.githubusercontent.com/16941896/139527925-e7d55df0-a385-40d0-a033-5780cd607189.png)

**Comment by ricky-hammers** [comment]
> @Bradw-17 Do you still have the image that's not working available? The guys that wrote the tzlocal librarys **_JUST_** released a new version and I'd like to see if it fixes your issue. If so can you do this:
> 
> ```
> sudo pip3 uninstall tzlocal
> sudo pip3 install tzlocal
> ```
> 
> Let me know if it helps

that did the trick for me as well! thanks a ton
