### ISSUE TITLE
Weather board icons

### ISSUE THREAD

**Issue by opaulhus** [riffnshred/nhl-led-scoreboard#337]
Using the OWM feed for my weather board, and the icons on the top right of the current weather page don't seem to change regardless of conditions. I get the partly sunny icon (cloud hiding sun) icon.

**Comment by falkyre** [comment]
Take a look in the logs and see if you see lines like this:

`2021-11-19 07:24:12 INFO ['11/19 07:24 AM', '\uf013', 'Cloudy', '-5.3C', '-14.2C', '81%', '-8.1C']`
`2021-11-19 07:24:12 INFO ['37.0 kph', 'SSE', '\uf05b', '0.0 kph', '1017.0 hPa', '\uf088', '24.1 km']`

The icon is defined by what's being sent from OWM.   Are your conditions changing in the logs?  What does the conditions show for your location if you go to www.openweathermap.org and check?
