### ISSUE TITLE
modulenotfounderror: no Module named 'cairosvg'

### ISSUE THREAD

**Issue by kevingc94** [riffnshred/nhl-led-scoreboard#343]
After the installation when running the main.py the code stops trying to import cairosvg with error message modulenotfounderror: no Module named 'cairosvg'

I installed cairosvg and even installed under pip3 Install cairosvg.

when running cairosvg --help I get all the messages and instructions on how to use it.

I did a manual installation. Raspberry Pi4.

Any help would be highly appreciated!

Thanks!
Kevin

**Comment by falkyre** [comment]
Couple of questions first.  What Raspberry Pi OS are you using?  The latest, which is Bullseye?  Or the last version?  Which is Buster (or to make it easier, how did you download it?  from raspberry pi or through the raspberry pi imager)?

Second question, when did you clone the repo?

The reason I ask is that it appears that the install might have not completely properly.  And we have found some issues with the matrix library  and Python versions greater than 3.8 that we just fixed earlier tonight.

**Comment by kevingc94** [comment]
Running the command Sudo Pip3 install cairosvg solved the problem

For reference:

Raspbian GNU/Linux 10 (buster)
The PI came with a SD with raspbian already installed.
I cloned yesterday around 8 pm Easter Time.
I am using Python3 3.7.3.

**Comment by falkyre** [comment]
Good to hear that the sudo pip3 install worked,  everything working for you now?

**Comment by kevingc94** [comment]
Right now I am just having a few issues with the display on the LED board. Trying to solve that at the moment. I can some sort of see the display, but pretty bad flickering.

I don't recall seeing issues regarding cairosvg during the install.

![16375156165154537994955992662110](https://user-images.githubusercontent.com/94727396/142772570-2a517f83-9fb5-4cfb-9851-2543668c5c63.jpg)

**Comment by riffnshred** [comment]
Check your ribbon cable and make sure its well sit in the socket on both ends. Also make sure the bottom of the Bonnet or HAT does not touch the raspberry pi. Make sure its isolated with electrical tape or a few layers of kapton tape. 

If you have not dont the antiflicker mod, there will be flickering regardless

**Comment by riffnshred** [comment]
Closing because the main issue is solved
