### ISSUE TITLE
Issues Running Final Display

### ISSUE THREAD

**Issue by Kanuck89** [riffnshred/nhl-led-scoreboard#361]
Hi,

I have followed through the set up instructions for the first time and am having issues with the final display. I am able to get "Hello world!" to scroll on the screen. and my config.json file passes the nhl setup validation.

However, when I go to run it through Supervisor, I receive a 'fatal' state with a description of 'exited too quickly'. Checking the logs on supervisor I see the comment of "python3: can't open file '/home/pi/nhl-led-scoreboard/runtext.py': [Errno 2] No such file or directory".

![image](https://user-images.githubusercontent.com/97643478/149245915-7768db53-07d8-4913-8dc1-7c2f9b51f490.png)

Any thoughts on what could be the issue? I'm rather new to this so I'm sure more information is needed to help describe the issue. 

Thanks

**Comment by falkyre** [comment]
If you are getting fatal errors in supervisor, the best first step would be to not use supervisor.  The tail -f stderr doesn't always work for some reason.  Take what your command line is for supervisor and run the command in a terminal.  Then you'll get the output live and when it crashes, you'll see exactly what error causes the crash.   Once you get that, reply to this thread and then @riffnshred or myself can figure out where things are crashing.

**Comment by Kanuck89** [comment]
Thanks for the feedback.

Executing the command line in a ssh terminal shows the LED display and cycles through the different scoreboards. However only if I'm in the 'nhl-led-scoreboard' directory as shown in the first screenshot. From there I checked the directory in the scoreboard.conf file, but I believe everything is as it should be? 

![image](https://user-images.githubusercontent.com/97643478/149384975-97fdff87-1fe9-48eb-88bb-5bf265b1dc73.png)

![image](https://user-images.githubusercontent.com/97643478/149388203-403a550c-62c0-44b5-8503-a526f011cbd8.png)

**Comment by Kanuck89** [comment]
After rebooting again appears I can now control and launch it from supervisor. Not sure why it wasn't working previously after the command line update as I went through this process a number of times with no success. 

Anyways, appreciate the quick feedback and support. I'll go ahead and close this issue with this comment.

**Comment by riffnshred** [comment]
tis the motto of all programmer: "It works now, I don't know why ¯\_(ツ)_/¯"
