### ISSUE TITLE
Led Matrix issues 

### ISSUE THREAD

**Issue by daz22** [riffnshred/nhl-led-scoreboard#365]
**Describe the bug**
Follow instruction and everything seems to be working but issues with the display. I have two RGB LED Matrix boards and i'm getting this same issue with both boards. 

Pi3 
Adafruit Hat w/RTC 
no anti flicker 
![20220124_213923](https://user-images.githubusercontent.com/66088770/150904015-2fd66d5e-e16b-4c68-9ec9-ea6242645bee.jpg)

**Comment by pjockey** [comment]
How are you powering the unit? I see a barrel jack lying on the carpet. You should power via the Adafruit Hat, not the Pi.

**Comment by daz22** [comment]
I have 5v 4A going to the hat and the Cana power supply for the pi

**Comment by daz22** [comment]
![20220124_223614.jpg](https://user-images.githubusercontent.com/66088770/150906428-70c7ee99-b690-4e86-a6b0-f97e5617701f.jpg)

**Comment by pjockey** [comment]
OK. I thought you should be able to power up everything by powering just the Hat. 

You should try the anti flicker. I makes a world of difference. Do you have a breadboard wire you can place in the Hat to try the anti flicker?

**Comment by riffnshred** [comment]
those missing lines are caused by a miss connection of one of the pins of the data port or cable or miss connection of one the pins that connect the HAT to the raspberry pi. If you have one, use your multimeter in the Continuity mode to probe where the missing connection is.

**Comment by daz22** [comment]
Ok! I will try that!

**Comment by daz22** [comment]
Check all the pins good continuity to all the pins.

**Comment by riffnshred** [comment]
So it could also be a faulty ribbon cable. if you play with it while the screen run, do you see something happen ? did you buy the panel also from Adafruit? or somewhere else. at the point I would go on their forum or discord for help as your problem is not related to the nhl-scoreboard software.

**Comment by Brune04** [comment]
Did you ever figure this out? I'm having the exact same issue

**Comment by daz22** [comment]
@Brune04
