### ISSUE TITLE
Is there a way to just launch the clock?

### ISSUE THREAD

**Issue by jediempi** [riffnshred/nhl-led-scoreboard#386]
I love this board! It works fantastic! I run it alongside the MLB, NFL, and NBA boards with Supervisor. I would love to be able to launch the clock on its own as an option. The clock is nice and elegant and looks really good. Is there a command line I can run to just run the clock?

Thanks!

**Comment by falkyre** [comment]
If you just set clock as the board for each state in the config file, it should just show the clock.

**Comment by jediempi** [comment]
Worked like a charm. I copied the directory and can now launch the Hockey board or just the clock from Supervisor. Thank you very much!
