### ISSUE TITLE
Shots counter and powerplay indicator

### ISSUE THREAD

**Issue by desigi** [riffnshred/nhl-led-scoreboard#4]
I'm not sure if the API provides this info, but a shot counter for each team and a powerplay indicator would be really nice.

**Comment by riffnshred** [comment]
![received_695963627570975](https://user-images.githubusercontent.com/16941896/68322221-07d6d880-0091-11ea-82ae-057e3e94339a.jpeg)
![received_2607318649326274](https://user-images.githubusercontent.com/16941896/68322249-158c5e00-0091-11ea-86b1-55766912353e.jpeg)

It is in the plan my friend, and more. These are just draft FYI. Im testing different things right now.

Everything you see on the NHL.com comes from that API.

**Comment by desigi** [comment]
Very nice. Great work!

**Comment by riffnshred** [comment]
Thanks 8)

**Comment by riffnshred** [comment]
Added in V1.1.1
