### ISSUE TITLE
LED matrix showing with light blue tint

### ISSUE THREAD

**Issue by rshadle22** [riffnshred/nhl-led-scoreboard#403]
**Describe the bug**
I'm unsure if this bug is due to the code or the way the RGB bonnet is set up with the hardware. The top portion of the LED matrix is shown with a light blue tint. Many of the whites are showing as light blue and reconnecting the bonnet to the raspberry pi did not fix the issue. I can't seem to find anything online that would help resolve this issue. Came here for some assistance or direction on how to troubleshoot.

![20221220_190302](https://user-images.githubusercontent.com/46681991/208797839-424d1cc3-b541-494b-bec9-08929e0d25f2.jpg)

**Logs**
N/A

**Your config file**
![20221220_191147](https://user-images.githubusercontent.com/46681991/208797862-24529812-e7fb-4d93-9b07-5aa4d967dafa.jpg)
![20221220_191157](https://user-images.githubusercontent.com/46681991/208797863-57dff3f4-4233-408a-8c0d-905a85cfb8f4.jpg)

**Hardware you are using**
- Raspberry pi 3 model A+
- The Matrix driver - Adafruit Bonnet
- Anti-flicker mod - no
- Adafruit 64x32 LED matrix

**Software**
- V 1.6.10

**Comment by riffnshred** [comment]
There is a misconnection or a short somewhere. Make sure the bottom of the Bonnet does not touch anything on the raspberry pi and that the data cable is well seated in both sockets.

**Comment by rshadle22** [comment]
Okay thanks! I'll try and make sure those connections are tightened properly.

**Comment by rshadle22** [comment]
Forgot to update this issue. There was a short with the dashboard and I was able to fix it by making sure the bonnet didn't touch the raspberry pi. Appreciate the help!
