### ISSUE TITLE
I'm stuck in the Loading Loop, but I think I have a different issue than the others.

### ISSUE THREAD

**Issue by Undertrader12** [riffnshred/nhl-led-scoreboard#429]
I did a fresh install of nhl-led-scoreboard and I ran the update (used git clone) and I did the uninstall and install of tzlocal and it didn't fix it.  It still loops on the loading screen.

If I run this command in the terminal:
sudo python3 src/main.py --led-gpio-mapping=adafruit-hat-pwm --led-brightness=60 --led-slowdown-gpio=2

I get the following:
INFO: Validating config.json.....
INFO: config.json passes validation
Failed to Get the list of Teams. 5 attempt remaining.
HTTPConnectionPool(host='statsapi.web.nhl.com', port=80): Max retries exceeded with url: /api/v1/teams?expand=team.roster,team.stats,team.schedule.previous,team.schedule.next (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xaff17e10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Failed to Get the list of Teams. 4 attempt remaining.
HTTPConnectionPool(host='statsapi.web.nhl.com', port=80): Max retries exceeded with url: /api/v1/teams?expand=team.roster,team.stats,team.schedule.previous,team.schedule.next (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xaff17d50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Failed to Get the list of Teams. 3 attempt remaining.
HTTPConnectionPool(host='statsapi.web.nhl.com', port=80): Max retries exceeded with url: /api/v1/teams?expand=team.roster,team.stats,team.schedule.previous,team.schedule.next (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xaff17dd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Failed to Get the list of Teams. 2 attempt remaining.
HTTPConnectionPool(host='statsapi.web.nhl.com', port=80): Max retries exceeded with url: /api/v1/teams?expand=team.roster,team.stats,team.schedule.previous,team.schedule.next (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xaff17ed0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Failed to Get the list of Teams. 1 attempt remaining.
HTTPConnectionPool(host='statsapi.web.nhl.com', port=80): Max retries exceeded with url: /api/v1/teams?expand=team.roster,team.stats,team.schedule.previous,team.schedule.next (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xaff17ef0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Failed to refresh the Status data. 5 attempt remaining.
HTTPConnectionPool(host='statsapi.web.nhl.com', port=80): Max retries exceeded with url: /api/v1/gameStatus (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xaff17d70>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Failed to refresh the Status data. 4 attempt remaining.
HTTPConnectionPool(host='statsapi.web.nhl.com', port=80): Max retries exceeded with url: /api/v1/gameStatus (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xaff17e30>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Failed to refresh the Status data. 3 attempt remaining.
HTTPConnectionPool(host='statsapi.web.nhl.com', port=80): Max retries exceeded with url: /api/v1/gameStatus (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xaff17d30>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Failed to refresh the Status data. 2 attempt remaining.
HTTPConnectionPool(host='statsapi.web.nhl.com', port=80): Max retries exceeded with url: /api/v1/gameStatus (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xaff17e10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Failed to refresh the Status data. 1 attempt remaining.
HTTPConnectionPool(host='statsapi.web.nhl.com', port=80): Max retries exceeded with url: /api/v1/gameStatus (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xaff17f70>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Failed to refresh the list of games. 5 attempt remaining.
HTTPConnectionPool(host='statsapi.web.nhl.com', port=80): Max retries exceeded with url: /api/v1/schedule?date=2023-11-9&expand=schedule.linescore (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb03f3b10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Failed to refresh the list of games. 4 attempt remaining.
HTTPConnectionPool(host='statsapi.web.nhl.com', port=80): Max retries exceeded with url: /api/v1/schedule?date=2023-11-9&expand=schedule.linescore (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb03f3a50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Failed to refresh the list of games. 3 attempt remaining.
HTTPConnectionPool(host='statsapi.web.nhl.com', port=80): Max retries exceeded with url: /api/v1/schedule?date=2023-11-9&expand=schedule.linescore (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb03f3b30>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Failed to refresh the list of games. 2 attempt remaining.
HTTPConnectionPool(host='statsapi.web.nhl.com', port=80): Max retries exceeded with url: /api/v1/schedule?date=2023-11-9&expand=schedule.linescore (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb03f3a70>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Failed to refresh the list of games. 1 attempt remaining.
HTTPConnectionPool(host='statsapi.web.nhl.com', port=80): Max retries exceeded with url: /api/v1/schedule?date=2023-11-9&expand=schedule.linescore (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb03f3b10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Traceback (most recent call last):
  File "src/main.py", line 156, in <module>
    run()
  File "src/main.py", line 61, in run
    data = Data(config)
  File "/home/pi/nhl-led-scoreboard/src/data/data.py", line 180, in __init__
    self.refresh_playoff()
  File "/home/pi/nhl-led-scoreboard/src/data/data.py", line 486, in refresh_playoff
    self.playoffs = nhl_api.playoff(self.status.season_id)
AttributeError: 'list' object has no attribute 'season_id'

**Comment by falkyre** [comment]
Read the front page of the repo on why this project is on hold and broken right now.  The NHL API is toast so that's causing the errors.  The web site that we pull the info from is gone.
