### ISSUE TITLE
Show Future Game

### ISSUE THREAD

**Issue by harmgsn** [riffnshred/nhl-led-scoreboard#46]
Feature enhancement request:  Instead of saying "No Game Today" -- show when the next game is and against who...  similar to the "Pre-Game State", but just add the date of the upcoming game... the "No Game Today" is sad...

**Comment by riffnshred** [comment]
There is no more "no game today" for V1. Want to join in on the Beta testing ? Join the discord chanel. https://discord.gg/CWa5CzK
