### ISSUE TITLE
Date on final score does not update

### ISSUE THREAD

**Issue by desigi** [riffnshred/nhl-led-scoreboard#5]
When I run the scoreboard for multiple days, the final scores on game days always shows the initial date that the scoreboard was started on. 

In the attached image the scoreboard was started on November 12th and the score shown from November 16th still shows the Nov. 12th date.
![IMG_20191117_013839](https://user-images.githubusercontent.com/1163052/69004080-41061880-08db-11ea-89cb-f3261c6eee53.jpg)

**Comment by riffnshred** [comment]
Fixed. It should refresh the date when it switches to a new day between noon and 1pm. Let me know if it didn't work on your end.
