### ISSUE TITLE
Suggestion to integrate Supervisor to monitor/restart the process

### ISSUE THREAD

**Issue by desigi** [riffnshred/nhl-led-scoreboard#50]
I used to use `nohup` and `&` to detach the process from my terminal and run it in the background, but I would notice that sometimes the process would just fail and I'd have to log back in and run the process again.

I would suggest using something like Supervisor to monitor the process and restart it automatically if it stops. This is the config file that I am currently running:
```
[program:nhl]
command=python3 /home/pi/nhl-board-dev/src/main.py --led-gpio-mapping=adafruit-hat-pwm --led-brightness=30 --led-slowdown-gpio=2
autostart=true
autorestart=true
stderr_logfile=/var/log/nhl.err.log
stdout_logfile=/var/log/nhl.out.log
```

**Comment by falkyre** [comment]
That's what I'm doing. Others use screen or tmux but there's no restart. You can do the same with systemd if you want.

**Comment by falkyre** [comment]
And bonus is you can have a web interface to your processes with supervisor

**Comment by riffnshred** [comment]
Will definitely test that out this weekend and maybe integrate that for V1 release

**Comment by riffnshred** [comment]
this is now one of our recommended solution as it allows controle using your phone and to switch to the MLB easily
