### ISSUE TITLE
day start

### ISSUE THREAD

**Issue by rhazzed** [riffnshred/nhl-led-scoreboard#52]
Is there a way to change the day start time? I changed the time in the config file but it has no effect.  Sometimes it says no game today or its shows the final score of the last game up to just a couple hours before a new game starts.  It would be nice to have a new day start earlier in the day/AM.

**Comment by riffnshred** [comment]
Its coming in V1. Beta version is currently being tested, Check the beta branch if you want to try it out, and join the discord channel.
