### ISSUE TITLE
src/renderer/main.py lines 154/159 need to come before the "if" logic now above them

### ISSUE THREAD

**Issue by ka9cql** [riffnshred/nhl-led-scoreboard#61]
In src/renderer/main.py - Picking up the home and the away team's scores on lines 154 and 159 need to occur regardless of whether the "if" tests two lines above them are true or false.

The fix is to move line 154 to 152, and move line 159 to 157.  This will guarantee that a new goal from either team will be recorded, regardless of whether that team is in your favorite list.

**Comment by riffnshred** [comment]
Fixed. Thank you so much !!!

**Comment by ka9cql** [comment]
No problem!
Thanks for all your incredible energy and diligence!!  (Not to mention this wicked cool scoreboard!!)
