### ISSUE TITLE
Team point total differing between team summary and wild card boards

### ISSUE THREAD

**Issue by cipriani14** [riffnshred/nhl-led-scoreboard#68]
Last night after the Blues game ended, the Team Summary board displayed their point total before the game (88), while the wild_card standings board updated with their new point total (90).

An hour or so later, the Stars game ended, and the same thing happened. The team summary point total stayed the same, while the wild_card board point total reflected the one point they earned during the game. 

I didn't think the point total for either board updated until the next day, so I had been restarting the board a few minutes after the games end to see updated point totals. Glad it's kinda/sorta working, though.

**Comment by riffnshred** [comment]
Fixed in V1.1.1
