### ISSUE TITLE
ModuleNotFoundError: No module named 'ephem'

### ISSUE THREAD

**Issue by ThePapatech** [riffnshred/nhl-led-scoreboard#71]
I have run through the instructions multiple time and have reinstalled pip but still I get this error when running the scoreboard:

pi@scoreboard:~/nhl-led-scoreboard $ sudo python3 src/main.py --led-gpio-mapping=adafruit-hat-pwm --led-brightness=60 --led-slowdown-gpio=2
Traceback (most recent call last):
  File "src/main.py", line 9, in <module>
    from dimmer import Dimmer
  File "/home/pi/nhl-led-scoreboard/src/dimmer.py", line 1, in <module>
    import ephem
ModuleNotFoundError: No module named 'ephem'

I have been chasing it all day and have googled myself into many blackholes! Any help is appreciated.

**Comment by riffnshred** [comment]
You installed PIP or PIP3?

**Comment by ThePapatech** [comment]
I have tried both...here is what it came back with last time...

pi@scoreboard:~ $ sudo apt install git python3-pip
Reading package lists... Done
Building dependency tree
Reading state information... Done
git is already the newest version (1:2.20.1-2+deb10u1).
python3-pip is already the newest version (18.1-5+rpt1).
0 upgraded, 0 newly installed, 0 to remove and 15 not upgraded.

**Comment by joshkay** [comment]
Try running the install script again.

**Comment by M4lwar** [comment]
I had same issue, had to manually install each package calling pip3.

**Comment by ThePapatech** [comment]
I will try the script again.

**Comment by ThePapatech** [comment]
I re-ran the script again and now it shows the scoreboard. Not sure what made it work but thanks for the push of ideas to get me back on track!

**Comment by riffnshred** [comment]
Glad it finally worked. Enjoy!!
