### ISSUE TITLE
Issue using configuration tool

### ISSUE THREAD

**Issue by jeepdrvr71** [riffnshred/nhl-led-scoreboard#83]
**Describe the bug**
Got the following error when running the configuration tool.

Error making backup of config/config.json. Error: [Errno 2] No such file or directory: 'config/config.json'

**Hardware you are using**
- Raspberry pi model= Pi Zero w/ WiFi
- The Matrix driver (Adafruit Bonnet or Adafruit HAT)= Adafruit Hat
- Anti-flicker=Yes

**Software**
-Latest Raspian Lite. This was a fresh install. No previous versions of NHL LED Scoreboard on the SD Card

**Comment by riffnshred** [comment]
All good this is normal ! I'll see if it's possible to turn that message into a warning instead! Thanks for reporting !!!!
