### ISSUE TITLE
COVID_19 board time 12/24 hour

### ISSUE THREAD

**Issue by ruchoff** [riffnshred/nhl-led-scoreboard#85]
**Description**
Have the time displayed on the covid_19 board be displayed in the time format set in the time_format config variable.

**Comment by jeepdrvr71** [comment]
I have a red line that is now popping up on the bottom of the Covid-19 screeens. Is this some kind of indicator?

**Comment by jeepdrvr71** [comment]
FYI-I restarted the program and the red line went away.

**Comment by riffnshred** [comment]
Its the network issue indicator. It was on for about 40min because the Covid 19 API was down.

**Comment by ntjoumas** [comment]
I have added in support to utilize format for covid_19 board from config.json. Will issue PR for changes in dev branch shortly.

**Comment by riffnshred** [comment]
the covid 19 board is no more since V1.6.0 as this was a temporary feature after the NHL 2020 season got canceled.
