### ISSUE TITLE
---- being displayed in next game

### ISSUE THREAD

**Issue by SL-8596** [riffnshred/nhl-led-scoreboard#89]
**Describe the bug**
Intermittently for Next Game ---- would show up, the rest of the time the March 29th game info would show.

**Your config file**
{
    "debug": true,
    "live_mode": true,
    "preferences": {
        "time_format": "12h",
        "end_of_day": "05:00",
        "live_game_refresh_rate": 10,
        "teams": [
            "Golden Knights",
            "Blackhawks"
        ],
        "sog_display_frequency": 4
    },
    "goal_animations": {
        "pref_team_only": true
    },
    "states": {
        "off_day": [
            "team_summary",
            "standings",
            "clock"
        ],
        "scheduled": [
            "scoreticker",
            "team_summary",
            "standings",
            "clock"
        ],
"intermission": [
            "team_summary",
            "scoreticker"
        ],
        "post_game": [
            "scoreticker",
            "team_summary",
            "standings",
            "clock"
        ]
    },
    "boards": {
        "scoreticker": {
            "preferred_teams_only": true,
            "rotation_rate": 5
        },
        "standings": {
            "preferred_standings_only": true,
            "standing_type": "conference",
            "divisions": "pacific",
            "conference": "western"
        },
        "clock": {
            "duration": 15,
            "hide_indicator": false
        }
    },
    "sbio": {
        "dimmer": {
            "enabled": true,
            "source": "software",
            "frequency": 5,
            "light_level_lux": 400,
            "mode": "always",
            "sunset_brightness": 15,
            "sunrise_brightness": 60
        },
        "pushbutton": {
            "enabled": false,
            "bonnet": true,
            "pin": 25,
            "reboot_duration": 2,
            "reboot_override_process": "",
            "display_reboot": true,
            "poweroff_duration": 10,
            "poweroff_override_process": "",
            "display_halt": true,
            "state_triggered1": "clock",
            "state_triggered1_process": ""
        }
    }
}

**Hardware you are using**
- Raspberry pi model
- The Matrix driver (Adafruit Bonnet or Adafruit HAT)
- Anti-flicker mod or not? 

**Software**
-v1.1.3

**Comment by riffnshred** [comment]
I can't replicate this. I'll keep digging but let me know if this still happens or happens again. I'll keep the issue open for now.
