### ISSUE TITLE
Elecrow 64x64 matrix with Adafruit RGB Bonnet color problem

### ISSUE THREAD

**Issue by purist69** [riffnshred/nhl-led-scoreboard#93]
The colors are incorrect on the Elecrow 64x64 led matrix panel, this can be resolved by swapping pins/wires:

G1->B1
G2->B2
B1->R1
B2->R2
R1->G1
R2->G2

**Comment by riffnshred** [comment]
![20200331_1450591 1](https://user-images.githubusercontent.com/16941896/78088046-046e2180-7391-11ea-8550-046516de1158.jpg)

**Comment by falkyre** [comment]
You can also use --led-rgb-sequence flag that the RGB library has.

**Comment by purist69** [comment]
wish I would have known that before I spent a couple of hours mucking around.  Reading helps... :)

**Comment by falkyre** [comment]
I missed it myself. Came across it while looking for something else.
